### ISSUE TITLE
[Feature Request] Environment variable to disable `chown` in scripts

### ISSUE THREAD

**Issue by Peaches491** [linuxserver/docker-baseimage#32]
It would be nice to have an environment variable for disabling the various `chown` calls throughout the various init scripts. This would apply to the docker-baseimage as well as all of its child images. This would be immensely useful (just like the PUID and PGID variables) for enabling easily transportable docker containers to the masses. 

My experience:
While attempting to install `linuxserver/docker-muximux`, I was presented with the error

```
chown: changing ownership of '/config': Permission denied
```

This is because all of my docker volumes are mounted from a CIFS directory on the host machine. I have my NFS mounted with the uid/gid of `nobody:nogroup`, the same permissions I set for my docker containers. 

The `chown` fails under this configuration, preventing me from using your images without manual intervention on my part. A simple environment variable toggle would readily fix this. The toggle might looks something like the following

`if [ "$CHOWN_DISABLE" == "false" ]; then chown -R abc:abc /config; fi;`

**Comment by sparklyballs** [comment]
closed , image is deprecated.
