### ISSUE TITLE
[Feature Request] add environment variable for git branch in git dockers

### ISSUE THREAD

**Issue by icebal** [linuxserver/docker-baseimage#34]
an example is Mylar. when using the docker like normal, it pulls the main branch. what i propose is add a variable like gitbranch or branch, so when not used it defaults to main branch, and when used it calls the branch given. since this would be used by someone who wants/needs a specific branch i.e. develop/development there is no need to supply that to the user. this will help people using dockers for the holy trinity (sonarr, couchpotato, headphones/mylar) to troubleshoot or get issues resolved easier.

**Comment by icebal** [comment]
perfect example is here below, pulled from this docker repo https://github.com/aptalca/docker-plexrequests/blob/master/firstrun.sh

if [ -z "$BRANCH" ]; then
  BRANCH="master"
fi

echo "Selecting the desired branch"
echo "Using the $BRANCH branch"
git checkout -f $BRANCH

**Comment by sparklyballs** [comment]
this baseimage is deprecated in favour of 

https://github.com/linuxserver/docker-baseimage-alpine

or for apt only apps

https://github.com/linuxserver/docker-baseimage-xenial
